// flow-typed signature: 8c98eb737823b34c5399fc8ac0fac7a9
// flow-typed version: <<STUB>>/bakaeditor_vgithub:lunavod/BakaEditor/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bakaeditor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bakaeditor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bakaeditor/dist/bundle' {
  declare module.exports: any;
}

declare module 'bakaeditor/src/document' {
  declare module.exports: any;
}

declare module 'bakaeditor/src/editable' {
  declare module.exports: any;
}

declare module 'bakaeditor/src' {
  declare module.exports: any;
}

declare module 'bakaeditor/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bakaeditor/dist/bundle.js' {
  declare module.exports: $Exports<'bakaeditor/dist/bundle'>;
}
declare module 'bakaeditor/src/document.js' {
  declare module.exports: $Exports<'bakaeditor/src/document'>;
}
declare module 'bakaeditor/src/editable.js' {
  declare module.exports: $Exports<'bakaeditor/src/editable'>;
}
declare module 'bakaeditor/src/index' {
  declare module.exports: $Exports<'bakaeditor/src'>;
}
declare module 'bakaeditor/src/index.js' {
  declare module.exports: $Exports<'bakaeditor/src'>;
}
declare module 'bakaeditor/webpack.config.js' {
  declare module.exports: $Exports<'bakaeditor/webpack.config'>;
}
