// flow-typed signature: 9c26bb7f55c4868e2cf14dfdaf3d82ae
// flow-typed version: <<STUB>>/baobab-react_v^4.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'baobab-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'baobab-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'baobab-react/dist-modules/context' {
  declare module.exports: any;
}

declare module 'baobab-react/dist-modules/higher-order' {
  declare module.exports: any;
}

declare module 'baobab-react/dist-modules/hooks' {
  declare module.exports: any;
}

declare module 'baobab-react/dist-modules/mixins' {
  declare module.exports: any;
}

declare module 'baobab-react/dist-modules/utils/helpers' {
  declare module.exports: any;
}

declare module 'baobab-react/dist-modules/utils/prop-types' {
  declare module.exports: any;
}

declare module 'baobab-react/higher-order' {
  declare module.exports: any;
}

declare module 'baobab-react/hooks' {
  declare module.exports: any;
}

declare module 'baobab-react/mixins' {
  declare module.exports: any;
}

declare module 'baobab-react/prop-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'baobab-react/dist-modules/context.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/context'>;
}
declare module 'baobab-react/dist-modules/higher-order.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/higher-order'>;
}
declare module 'baobab-react/dist-modules/hooks.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/hooks'>;
}
declare module 'baobab-react/dist-modules/mixins.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/mixins'>;
}
declare module 'baobab-react/dist-modules/utils/helpers.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/utils/helpers'>;
}
declare module 'baobab-react/dist-modules/utils/prop-types.js' {
  declare module.exports: $Exports<'baobab-react/dist-modules/utils/prop-types'>;
}
declare module 'baobab-react/higher-order.js' {
  declare module.exports: $Exports<'baobab-react/higher-order'>;
}
declare module 'baobab-react/hooks.js' {
  declare module.exports: $Exports<'baobab-react/hooks'>;
}
declare module 'baobab-react/index' {
  declare module.exports: $Exports<'baobab-react'>;
}
declare module 'baobab-react/index.js' {
  declare module.exports: $Exports<'baobab-react'>;
}
declare module 'baobab-react/mixins.js' {
  declare module.exports: $Exports<'baobab-react/mixins'>;
}
declare module 'baobab-react/prop-types.js' {
  declare module.exports: $Exports<'baobab-react/prop-types'>;
}
