// flow-typed signature: 3a87b73fecde5a52eacb34792b26f882
// flow-typed version: <<STUB>>/decache_v^4.5.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'decache/decache' {
  declare module.exports: any;
}

declare module 'decache/lib/mymodule' {
  declare module.exports: any;
}

declare module 'decache/lib/othermodule' {
  declare module.exports: any;
}

declare module 'decache/setup' {
  declare module.exports: any;
}

declare module 'decache/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'decache/decache.js' {
  declare module.exports: $Exports<'decache/decache'>;
}
declare module 'decache/lib/mymodule/index' {
  declare module.exports: $Exports<'decache/lib/mymodule'>;
}
declare module 'decache/lib/mymodule/index.js' {
  declare module.exports: $Exports<'decache/lib/mymodule'>;
}
declare module 'decache/lib/othermodule.js' {
  declare module.exports: $Exports<'decache/lib/othermodule'>;
}
declare module 'decache/setup.js' {
  declare module.exports: $Exports<'decache/setup'>;
}
declare module 'decache/test/test.js' {
  declare module.exports: $Exports<'decache/test/test'>;
}
