// flow-typed signature: d7bcb895cb925e586c7ff346f6093e39
// flow-typed version: <<STUB>>/ejs-loader_v^0.3.5/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ejs-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ejs-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ejs-loader/__tests__/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ejs-loader/__tests__/index.test.js' {
  declare module.exports: $Exports<'ejs-loader/__tests__/index.test'>;
}
declare module 'ejs-loader/index' {
  declare module.exports: $Exports<'ejs-loader'>;
}
declare module 'ejs-loader/index.js' {
  declare module.exports: $Exports<'ejs-loader'>;
}
