// flow-typed signature: 8478ae135c68c67ecb3710c7f730f768
// flow-typed version: <<STUB>>/fitty_v^2.3.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fitty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fitty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fitty/dist/fitty.min' {
  declare module.exports: any;
}

declare module 'fitty/dist/fitty.module' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fitty/dist/fitty.min.js' {
  declare module.exports: $Exports<'fitty/dist/fitty.min'>;
}
declare module 'fitty/dist/fitty.module.js' {
  declare module.exports: $Exports<'fitty/dist/fitty.module'>;
}
